# ARTIFICIAL NEURAL NETWORKS
Case Study: SONAR — Detecting Mines vs. Rocks  
1️⃣ Business Objective  
Goal:  
To build an intelligent system that can automatically detect whether an underwater sonar signal is reflected from a metallic mine (potentially dangerous) or a harmless rock.  
This is vital for:  
•	Maritime safety: Prevent ships and submarines from colliding with mines.  
•	Naval defense: Identify and safely remove underwater mines.  
•	Resource exploration: Distinguish between useful metal structures and natural seabed objects.  
________________________________________
2️⃣ Problem Statement  
In underwater environments, sonar (sound navigation and ranging) is used to detect objects. However, raw sonar signals can be noisy and difficult for humans to interpret consistently.  
This dataset:  
•	Contains 208 sonar returns.  
o	111 are from metal cylinders (mines).  
o	97 are from rocks.   
•	Each sonar return is represented by 60 numeric features, each measuring the energy of the signal in a frequency band.

The problem:
👉 To train a Deep learning model that can learn the difference in signal patterns and classify new sonar signals as either Mine (M) or Rock (R) — accurately and reliably.
Dataset: "sonardataset.csv"  
**Features (Inputs)**  
•	There are 60 numerical variables, each representing the energy in a specific frequency band of the sonar signal.    
•	In the original dataset, they’re just unnamed columns V1, V2, ..., V60 — you can keep it clear and simple:    
2️⃣ Target (Output)     
•	The label is a single categorical variable indicating:    
o	"M" for Mine    
o	"R" for Rock  


## Tasks:    
## 1. Data Exploration and Preprocessing    
●	Begin by loading and exploring the "sonardataset.csv" dataset. Summarize its key features such as the number of samples, features, and classes.     
●	Execute necessary data preprocessing steps including data normalization, managing missing values.

In [1]:
# Load the Dataset 
import pandas as pd 

df = pd.read_csv("sonardataset.csv")

In [2]:
# Head of the Dataset 
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [3]:
# Tail of the Dataset 
df.tail()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [4]:
# Shape of the Dataset 
df.shape

(208, 61)

In [5]:
# Colmns of the Dataset
df.columns

Index(['x_1', 'x_2', 'x_3', 'x_4', 'x_5', 'x_6', 'x_7', 'x_8', 'x_9', 'x_10',
       'x_11', 'x_12', 'x_13', 'x_14', 'x_15', 'x_16', 'x_17', 'x_18', 'x_19',
       'x_20', 'x_21', 'x_22', 'x_23', 'x_24', 'x_25', 'x_26', 'x_27', 'x_28',
       'x_29', 'x_30', 'x_31', 'x_32', 'x_33', 'x_34', 'x_35', 'x_36', 'x_37',
       'x_38', 'x_39', 'x_40', 'x_41', 'x_42', 'x_43', 'x_44', 'x_45', 'x_46',
       'x_47', 'x_48', 'x_49', 'x_50', 'x_51', 'x_52', 'x_53', 'x_54', 'x_55',
       'x_56', 'x_57', 'x_58', 'x_59', 'x_60', 'Y'],
      dtype='object')

In [6]:
# General Information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [7]:
# Statistical Summary 
df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [8]:
# Checking Missing Values
df.isnull().sum().sum()

np.int64(0)

In [9]:
# Check duplicate Values
df.duplicated().sum()

np.int64(0)

In [10]:
# check outlier

import matplotlib.pyplot as plt 
import seaborn as sns 
plt.figure(figsize = (20,6))
# sns.boxplot(df)
# plt.show()

In [11]:
# Ouitlier Capping 
for i in df.select_dtypes(include = ['int','float']).columns:
    q1 = df[i].quantile(0.25)
    q3 = df[i].quantile(0.75)

    IQR = q1 - q3 
    lower_bound = q1 - 1.5*IQR
    upper_bound = q3 + 1.5*IQR

    df[i] = df[i].clip(lower_bound, upper_bound)

In [12]:
# Verify outlier 
import matplotlib.pyplot as plt 
import seaborn as sns 
plt.figure(figsize = (20,6))
# sns.boxplot(df)
# plt.show()

## 2. Model Implementation    
●	Construct a basic ANN model using your chosen high-level neural network library. Ensure your model includes at least one hidden layer.     
●	Divide the dataset into training and test sets.      
●	Train your model on the training set and then use it to make predictions on the test set.

In [13]:
# Construction of ANN Model 

from keras.models import Sequential 
from keras.layers import Dense 

from tensorflow.keras.callbacks import EarlyStopping 
early = EarlyStopping(monitor = 'val_accuracy', patience = 4)

# Creation of model having multi layer 
model = Sequential()
model.add(Dense(12, input_dim =60, activation = 'relu')) # 1st Layer Input layer

model.add(Dense(8, activation = 'relu')) # 2nd Layer or 1st Hidden Layer 
model.add(Dense(8, activation = 'relu')) # 2nd Hiddenn layer
model.add(Dense(4, activation = 'relu')) # 3rd Hidden layer

model.add(Dense(1, activation = 'sigmoid'))  # Output layer

C:\Users\ashah\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
# Target columns encoding 
import pandas as pd

# Create encoded target DataFrame
y_df = pd.DataFrame()

y_df["Y_encoded"] = df["Y"].map({
    "R": 0,
    "M": 1
})

# Add encoded column to original DataFrame
df = pd.concat([df, y_df], axis=1)

# Remove original categorical target
df.drop("Y", axis=1, inplace=True)

In [15]:
# Separate features and target
x = df.drop("Y_encoded", axis=1)
y = df["Y_encoded"]

In [16]:
# Divide the dataset into training and testin 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state= 42)

In [17]:
# Model compiling 
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [18]:
# ● Train your model on the training set and then use it to make predictions on the test set.

# Fit the Model 
history = model.fit(x,y, validation_split = 0.33, epochs = 50, batch_size = 10)

Epoch 1/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - accuracy: 0.6906 - loss: 0.6913 - val_accuracy: 0.0000e+00 - val_loss: 0.7133
Epoch 2/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6978 - loss: 0.6859 - val_accuracy: 0.0000e+00 - val_loss: 0.7359
Epoch 3/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6978 - loss: 0.6800 - val_accuracy: 0.0000e+00 - val_loss: 0.7843
Epoch 4/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6978 - loss: 0.6699 - val_accuracy: 0.0000e+00 - val_loss: 0.8504
Epoch 5/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6978 - loss: 0.6509 - val_accuracy: 0.0000e+00 - val_loss: 0.9260
Epoch 6/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.6344 - val_accuracy: 0.0000e+00 - val_loss: 1.0251
Epoch 7/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.6221 - val_accuracy: 0.0000e+00 - val_loss: 1.0838
Epoch 8/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.6163 - val_accuracy: 0.0000e+00 - val_loss: 1.1801
Epoch 9/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6978 - loss: 0.6111 - val_accuracy: 0.0000e+00 - val_loss: 1.1947
Epoch 10/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.6055 - val_accuracy: 0.0000e+00 - val_loss: 1.2446
Epoch 11/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.6004 - val_accuracy: 0.0000e+00 - val_loss: 1.2481
Epoch 12/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6978 - loss: 0.5913 - val_accuracy: 0.0000e+00 - val_loss: 1.3078
Epoch 13/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6978 - loss: 0.5815 - val_accuracy: 0.0000e+00 - val_loss: 1.3444
Epoch 14/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6978 - loss: 0.5714 - val_accuracy: 0.0000e+00 - val_loss: 1.3762
Epoch 15/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6978 - loss: 0.5538 - val_accuracy: 0.0000e+00 - val_loss: 1.4785
Epoch 16/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6978 - loss: 0.5364 - val_accuracy: 0.0000e+00 - val_loss: 1.5358
Epoch 17/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6978 - loss: 0.5172 - val_accuracy: 0.0000e+00 - val_loss: 1.5556
Epoch 18/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6978 - loss: 0.5015 - val_accuracy: 0.0000e+00 - val_loss: 1.7447
Epoch 19/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6978 - loss: 0.4844 - val_accuracy: 0.0000e+00 - val_loss: 1.6578
Epoch 20/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6978 - loss: 0.4698 - val_accuracy: 0.0000e+00 - val_loss: 1.9248
Epoch 21/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6978 - loss: 0.4527 - val_accuracy: 0.0000e+00 - val_loss: 1.8892
Epoch 22/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6978 - loss: 0.4416 - val_accuracy: 0.0000e+00 - val_loss: 1.9288
Epoch 23/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.4297 - val_accuracy: 0.0000e+00 - val_loss: 2.2799
Epoch 24/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6978 - loss: 0.4174 - val_accuracy: 0.0000e+00 - val_loss: 2.0409
Epoch 25/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6978 - loss: 0.4081 - val_accuracy: 0.0000e+00 - val_loss: 2.3670
Epoch 26/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6978 - loss: 0.4025 - val_accuracy: 0.0000e+00 - val_loss: 2.3235
Epoch 27/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6978 - loss: 0.3925 - val_accuracy: 0.0000e+00 - val_loss: 2.4351
Epoch 28/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6978 - loss: 0.3879 - val_accuracy: 0.0000e+00 - val_loss: 2.4546
Epoch 29/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6978 - loss: 0.3838 - val_accuracy: 0.0000e+00 - val_loss: 2.8522
Epoch 30/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6978 - loss: 0.3808 - val_accuracy: 0.0000e+00 - val_loss: 2.6182
Epoch 31/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7842 - loss: 0.3741 - val_accuracy: 0.0145 - val_loss: 2.7691
Epoch 32/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8633 - loss: 0.3739 - val_accuracy: 0.0145 - val_loss: 2.7135
Epoch 33/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8201 - loss: 0.3650 - val_accuracy: 0.0725 - val_loss: 2.6199
Epoch 34/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8705 - loss: 0.3611 - val_accuracy: 0.0580 - val_loss: 2.7329
Epoch 35/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8489 - loss: 0.3599 - val_accuracy: 0.0580 - val_loss: 2.7459
Epoch 36/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8705 - loss: 0.3557 - val_accuracy: 0.0580 - val_loss: 2.8626
Epoch 37/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8561 - loss: 0.3496 - val_accuracy: 0.0725 - val_loss: 2.9175
Epoch 38/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8849 - loss: 0.3440 - val_accuracy: 0.0725 - val_loss: 3.1035
Epoch 39/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8849 - loss: 0.3446 - val_accuracy: 0.0725 - val_loss: 2.8466
Epoch 40/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8705 - loss: 0.3360 - val_accuracy: 0.0725 - val_loss: 3.0630
Epoch 41/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8705 - loss: 0.3316 - val_accuracy: 0.0725 - val_loss: 3.0688
Epoch 42/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8993 - loss: 0.3278 - val_accuracy: 0.0725 - val_loss: 3.1479
Epoch 43/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8489 - loss: 0.3311 - val_accuracy: 0.0870 - val_loss: 2.8448
Epoch 44/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8921 - loss: 0.3306 - val_accuracy: 0.0725 - val_loss: 3.1258
Epoch 45/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8993 - loss: 0.3204 - val_accuracy: 0.0725 - val_loss: 3.4224
Epoch 46/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8993 - loss: 0.3192 - val_accuracy: 0.0725 - val_loss: 3.3647
Epoch 47/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8993 - loss: 0.3107 - val_accuracy: 0.0725 - val_loss: 3.3233
Epoch 48/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8921 - loss: 0.3194 - val_accuracy: 0.0725 - val_loss: 3.6406
Epoch 49/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8993 - loss: 0.3198 - val_accuracy: 0.1449 - val_loss: 3.0064
Epoch 50/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8777 - loss: 0.3079 - val_accuracy: 0.0725 - val_loss: 3.4442

In [19]:
# Make predictions on test data
y_pred_prob = model.predict(x_test)

print(y_pred_prob[:10])

# Convert Problities into classification
y_pred = (y_pred_prob >= 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
[[1.1796408e-03]
 [9.2761302e-03]
 [1.1081143e-01]
 [6.1124018e-03]
 [1.6103735e-02]
 [5.6036641e-03]
 [5.3624451e-01]
 [5.3624451e-01]
 [1.2319247e-04]
 [5.3624451e-01]]

In [20]:
# Compare with actual valus

compare = pd.DataFrame({
    "Actual Value" : y_test,
    "Predicted Value" : y_pred.flatten()
})
compare.head(10)

     Actual Value  Predicted Value
161             1                0
15              0                0
73              0                0
96              0                0
166             1                0
9               0                0
100             1                1
135             1                1
18              0                0
148             1                1

## 3. Hyperparameter Tuning    
●	Modify various hyperparameters, such as the number of hidden layers, neurons per hidden layer, activation functions, and learning rate, to observe their impact on model performance.     
●	Adopt a structured approach like grid search or random search for hyperparameter tuning, documenting your methodology thoroughly.

In [21]:
# Modify various hyperparameters, such as the number of hidden layers, neurons per hidden layer, activation functions,
# and learning rate, to observe their impact on model performance.

from keras.models import Sequential 
from keras.layers import Dense 

from tensorflow.keras.callbacks import EarlyStopping 
early = EarlyStopping(monitor = 'val_accuracy', patience = 4)

# Creation of model having multi layer 
model2 = Sequential()
model2.add(Dense(12, input_dim =60, activation = 'relu')) # 1st Layer Input layer

model2.add(Dense(10, activation = 'relu')) # 2nd Layer or 1st Hidden Layer 
model2.add(Dense(12, activation = 'sigmoid')) # 2nd Hiddenn layer
model2.add(Dense(6, activation = 'relu')) # 3rd Hidden layer

model2.add(Dense(1, activation = 'sigmoid'))  # Output layer

C:\Users\ashah\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
# Model2 Compiling 
model2.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [23]:
# Fit the Model 
history2 = model2.fit(x, y , validation_split = 0.30, epochs = 100, batch_size = 20)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 66ms/step - accuracy: 0.6690 - loss: 0.6694 - val_accuracy: 0.0000e+00 - val_loss: 0.8334
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6690 - loss: 0.6550 - val_accuracy: 0.0000e+00 - val_loss: 0.8975
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.6468 - val_accuracy: 0.0000e+00 - val_loss: 0.9449
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.6399 - val_accuracy: 0.0000e+00 - val_loss: 0.9606
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6690 - loss: 0.6364 - val_accuracy: 0.0000e+00 - val_loss: 0.9873
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6690 - loss: 0.6332 - val_accuracy: 0.0000e+00 - val_loss: 1.0177
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6690 - loss: 0.6300 - val_accuracy: 0.0000e+00 - val_loss: 1.0311
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.6277 - val_accuracy: 0.0000e+00 - val_loss: 1.0459
Epoch 9/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6267 - val_accuracy: 0.0000e+00 - val_loss: 1.0845
Epoch 10/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6237 - val_accuracy: 0.0000e+00 - val_loss: 1.0774
Epoch 11/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6225 - val_accuracy: 0.0000e+00 - val_loss: 1.0650
Epoch 12/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6209 - val_accuracy: 0.0000e+00 - val_loss: 1.0741
Epoch 13/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6192 - val_accuracy: 0.0000e+00 - val_loss: 1.0936
Epoch 14/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.6167 - val_accuracy: 0.0000e+00 - val_loss: 1.0828
Epoch 15/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6690 - loss: 0.6140 - val_accuracy: 0.0000e+00 - val_loss: 1.0780
Epoch 16/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6690 - loss: 0.6117 - val_accuracy: 0.0000e+00 - val_loss: 1.0859
Epoch 17/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6690 - loss: 0.6085 - val_accuracy: 0.0000e+00 - val_loss: 1.0786
Epoch 18/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.6055 - val_accuracy: 0.0000e+00 - val_loss: 1.1025
Epoch 19/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6690 - loss: 0.6005 - val_accuracy: 0.0000e+00 - val_loss: 1.0900
Epoch 20/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6690 - loss: 0.5966 - val_accuracy: 0.0000e+00 - val_loss: 1.0876
Epoch 21/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6690 - loss: 0.5928 - val_accuracy: 0.0000e+00 - val_loss: 1.1076
Epoch 22/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.5894 - val_accuracy: 0.0000e+00 - val_loss: 1.1490
Epoch 23/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.5832 - val_accuracy: 0.0000e+00 - val_loss: 1.1205
Epoch 24/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.5787 - val_accuracy: 0.0000e+00 - val_loss: 1.0963
Epoch 25/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6690 - loss: 0.5736 - val_accuracy: 0.0000e+00 - val_loss: 1.1472
Epoch 26/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6690 - loss: 0.5684 - val_accuracy: 0.0000e+00 - val_loss: 1.1620
Epoch 27/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6690 - loss: 0.5631 - val_accuracy: 0.0000e+00 - val_loss: 1.1667
Epoch 28/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.5575 - val_accuracy: 0.0000e+00 - val_loss: 1.1592
Epoch 29/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6690 - loss: 0.5525 - val_accuracy: 0.0000e+00 - val_loss: 1.1142
Epoch 30/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6621 - loss: 0.5463 - val_accuracy: 0.0000e+00 - val_loss: 1.1761
Epoch 31/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6897 - loss: 0.5396 - val_accuracy: 0.0000e+00 - val_loss: 1.1683
Epoch 32/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7034 - loss: 0.5335 - val_accuracy: 0.0000e+00 - val_loss: 1.2043
Epoch 33/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7034 - loss: 0.5303 - val_accuracy: 0.0000e+00 - val_loss: 1.2752
Epoch 34/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7103 - loss: 0.5233 - val_accuracy: 0.0000e+00 - val_loss: 1.2735
Epoch 35/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7103 - loss: 0.5170 - val_accuracy: 0.0000e+00 - val_loss: 1.2667
Epoch 36/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7586 - loss: 0.5111 - val_accuracy: 0.0000e+00 - val_loss: 1.2234
Epoch 37/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7586 - loss: 0.5047 - val_accuracy: 0.0000e+00 - val_loss: 1.2628
Epoch 38/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7655 - loss: 0.4992 - val_accuracy: 0.0000e+00 - val_loss: 1.3647
Epoch 39/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7586 - loss: 0.4956 - val_accuracy: 0.0159 - val_loss: 1.3468
Epoch 40/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7655 - loss: 0.4901 - val_accuracy: 0.0159 - val_loss: 1.3418
Epoch 41/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7586 - loss: 0.4872 - val_accuracy: 0.0476 - val_loss: 1.3663
Epoch 42/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7655 - loss: 0.4798 - val_accuracy: 0.1746 - val_loss: 1.1950
Epoch 43/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7793 - loss: 0.4780 - val_accuracy: 0.1746 - val_loss: 1.2294
Epoch 44/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7517 - loss: 0.4741 - val_accuracy: 0.0476 - val_loss: 1.4133
Epoch 45/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7448 - loss: 0.4698 - val_accuracy: 0.0476 - val_loss: 1.4366
Epoch 46/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7931 - loss: 0.4602 - val_accuracy: 0.1587 - val_loss: 1.3157
Epoch 47/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7862 - loss: 0.4584 - val_accuracy: 0.2222 - val_loss: 1.2439
Epoch 48/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7655 - loss: 0.4536 - val_accuracy: 0.2063 - val_loss: 1.3415
Epoch 49/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8000 - loss: 0.4501 - val_accuracy: 0.1270 - val_loss: 1.4460
Epoch 50/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7862 - loss: 0.4440 - val_accuracy: 0.1746 - val_loss: 1.4325
Epoch 51/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8069 - loss: 0.4379 - val_accuracy: 0.2063 - val_loss: 1.4392
Epoch 52/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8000 - loss: 0.4320 - val_accuracy: 0.2381 - val_loss: 1.3329
Epoch 53/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7862 - loss: 0.4297 - val_accuracy: 0.2381 - val_loss: 1.3365
Epoch 54/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8000 - loss: 0.4253 - val_accuracy: 0.2381 - val_loss: 1.3851
Epoch 55/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8207 - loss: 0.4190 - val_accuracy: 0.2381 - val_loss: 1.4664
Epoch 56/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8207 - loss: 0.4134 - val_accuracy: 0.2381 - val_loss: 1.4469
Epoch 57/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8345 - loss: 0.4097 - val_accuracy: 0.2698 - val_loss: 1.4389
Epoch 58/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8276 - loss: 0.4059 - val_accuracy: 0.2381 - val_loss: 1.5133
Epoch 59/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8276 - loss: 0.3999 - val_accuracy: 0.2698 - val_loss: 1.4627
Epoch 60/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8621 - loss: 0.3964 - val_accuracy: 0.2698 - val_loss: 1.4503
Epoch 61/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8414 - loss: 0.3896 - val_accuracy: 0.2381 - val_loss: 1.5798
Epoch 62/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8276 - loss: 0.3865 - val_accuracy: 0.2540 - val_loss: 1.5526
Epoch 63/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.3806 - val_accuracy: 0.2698 - val_loss: 1.5079
Epoch 64/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8621 - loss: 0.3771 - val_accuracy: 0.2698 - val_loss: 1.5644
Epoch 65/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8690 - loss: 0.3712 - val_accuracy: 0.2857 - val_loss: 1.4665
Epoch 66/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8759 - loss: 0.3696 - val_accuracy: 0.2857 - val_loss: 1.4718
Epoch 67/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8690 - loss: 0.3641 - val_accuracy: 0.2698 - val_loss: 1.5709
Epoch 68/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8621 - loss: 0.3595 - val_accuracy: 0.2698 - val_loss: 1.6383
Epoch 69/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8621 - loss: 0.3543 - val_accuracy: 0.3175 - val_loss: 1.5844
Epoch 70/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8828 - loss: 0.3555 - val_accuracy: 0.3333 - val_loss: 1.4990
Epoch 71/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8621 - loss: 0.3444 - val_accuracy: 0.2698 - val_loss: 1.6948
Epoch 72/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8759 - loss: 0.3397 - val_accuracy: 0.3016 - val_loss: 1.5793
Epoch 73/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8897 - loss: 0.3362 - val_accuracy: 0.3651 - val_loss: 1.4257
Epoch 74/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8966 - loss: 0.3335 - val_accuracy: 0.3175 - val_loss: 1.5826
Epoch 75/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8690 - loss: 0.3266 - val_accuracy: 0.3016 - val_loss: 1.6576
Epoch 76/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8966 - loss: 0.3267 - val_accuracy: 0.3333 - val_loss: 1.5858
Epoch 77/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8690 - loss: 0.3192 - val_accuracy: 0.3016 - val_loss: 1.6793
Epoch 78/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8621 - loss: 0.3133 - val_accuracy: 0.3492 - val_loss: 1.5789
Epoch 79/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8897 - loss: 0.3099 - val_accuracy: 0.3492 - val_loss: 1.5132
Epoch 80/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8897 - loss: 0.3049 - val_accuracy: 0.3016 - val_loss: 1.6718
Epoch 81/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8690 - loss: 0.3113 - val_accuracy: 0.2857 - val_loss: 1.8146
Epoch 82/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9034 - loss: 0.2970 - val_accuracy: 0.3651 - val_loss: 1.5445
Epoch 83/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8966 - loss: 0.2945 - val_accuracy: 0.3175 - val_loss: 1.6635
Epoch 84/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8897 - loss: 0.2903 - val_accuracy: 0.2857 - val_loss: 1.7743
Epoch 85/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8966 - loss: 0.2823 - val_accuracy: 0.3651 - val_loss: 1.5854
Epoch 86/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8966 - loss: 0.2840 - val_accuracy: 0.3333 - val_loss: 1.6937
Epoch 87/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8966 - loss: 0.2801 - val_accuracy: 0.2857 - val_loss: 1.8527
Epoch 88/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9103 - loss: 0.2734 - val_accuracy: 0.3333 - val_loss: 1.6928
Epoch 89/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9034 - loss: 0.2718 - val_accuracy: 0.3492 - val_loss: 1.6531
Epoch 90/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9103 - loss: 0.2670 - val_accuracy: 0.3333 - val_loss: 1.7206
Epoch 91/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9034 - loss: 0.2646 - val_accuracy: 0.2857 - val_loss: 1.8838
Epoch 92/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9103 - loss: 0.2599 - val_accuracy: 0.3492 - val_loss: 1.6714
Epoch 93/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9103 - loss: 0.2564 - val_accuracy: 0.3492 - val_loss: 1.7059
Epoch 94/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9103 - loss: 0.2517 - val_accuracy: 0.3333 - val_loss: 1.8628
Epoch 95/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9172 - loss: 0.2494 - val_accuracy: 0.3492 - val_loss: 1.7903
Epoch 96/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8966 - loss: 0.2509 - val_accuracy: 0.3333 - val_loss: 1.9438
Epoch 97/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9172 - loss: 0.2440 - val_accuracy: 0.3492 - val_loss: 1.6807
Epoch 98/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9172 - loss: 0.2407 - val_accuracy: 0.3333 - val_loss: 1.8777
Epoch 99/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9379 - loss: 0.2340 - val_accuracy: 0.3492 - val_loss: 1.8023
Epoch 100/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9241 - loss: 0.2327 - val_accuracy: 0.3651 - val_loss: 1.7691

In [24]:
# Prediction 
y2_pred = model2.predict(x_test)

y2_pred 

# Convert probablity into classification
y2_prediction = (y2_pred >= 0.5).astype(int)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

In [25]:
# Compare with actual valus

compare = pd.DataFrame({
    "Actual Value" : y_test,
    "Predicted Value" : y2_prediction.flatten()
})
compare.head(10)

     Actual Value  Predicted Value
161             1                0
15              0                0
73              0                0
96              0                0
166             1                1
9               0                0
100             1                1
135             1                1
18              0                0
148             1                1

In [26]:
!pip install keras-tuner

Requirement already satisfied: keras-tuner in c:\users\ashah\anaconda3\lib\site-packages (1.4.8)
Requirement already satisfied: keras in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (3.15.0)
Requirement already satisfied: packaging in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (2.32.5)
Requirement already satisfied: kt-legacy in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (1.82.1)
Requirement already satisfied: protobuf in c:\users\ashah\anaconda3\lib\site-packages (from keras-tuner) (7.35.1)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\ashah\anaconda3\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (2.5.0)
Requirement already satisfied: numpy in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (2.3.5)
Requirement already satisfied: rich in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (14.2.0)
Requirement already satisfied: namex in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\ashah\anaconda3\lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ashah\anaconda3\lib\site-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ashah\anaconda3\lib\site-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ashah\anaconda3\lib\site-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ashah\anaconda3\lib\site-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ashah\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ashah\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\ashah\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [27]:
!pip install scikeras

Requirement already satisfied: scikeras in c:\users\ashah\anaconda3\lib\site-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in c:\users\ashah\anaconda3\lib\site-packages (from scikeras) (3.15.0)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\ashah\anaconda3\lib\site-packages (from scikeras) (1.7.2)
Requirement already satisfied: absl-py in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.5.0)
Requirement already satisfied: numpy in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.3.5)
Requirement already satisfied: rich in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (14.2.0)
Requirement already satisfied: namex in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (3.14.0)
Requirement already satisfied: optree in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.1)
Requirement already satisfied: ml-dtypes in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\ashah\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (25.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ashah\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ashah\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ashah\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ashah\anaconda3\lib\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ashah\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ashah\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\ashah\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)

In [28]:
# ============================================================
# ANN HYPERPARAMETER TUNING USING GRID SEARCH
# Binary Classification
# ============================================================
import warnings
warnings.filterwarnings("ignore")
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV


# ------------------------------------------------------------
# 1. Create ANN model
# ------------------------------------------------------------

def create_model(optimizer="adam", neurons=8):

    model = Sequential()

    # Input + Hidden Layer
    model.add(
        Dense(
            neurons,
            input_dim=x_train.shape[1],
            activation="relu"
        )
    )

    # Second Hidden Layer
    model.add(Dense(8, activation="relu"))

    # Output Layer - Binary Classification
    model.add(Dense(1, activation="sigmoid"))

    # Compile
    model.compile(
        optimizer=optimizer,
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    return model


# ------------------------------------------------------------
# 2. Wrap ANN for GridSearchCV
# ------------------------------------------------------------

model = KerasClassifier(
    model=create_model,
    verbose=0
)


# ------------------------------------------------------------
# 3. Define parameters for Grid Search
# ------------------------------------------------------------

param_grid = {
    "model__neurons": [8, 12, 16],
    "model__optimizer": ["adam", "rmsprop"],
    "batch_size": [10, 20],
    "epochs": [30, 50]
}


# ------------------------------------------------------------
# 4. Apply Grid Search
# ------------------------------------------------------------

grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=1
)


# ------------------------------------------------------------
# 5. Run Grid Search on training data
# ------------------------------------------------------------

grid_result = grid.fit(
    x_train,
    y_train
)


# ------------------------------------------------------------
# 6. Display best parameters
# ------------------------------------------------------------

print("Best Parameters:")
print(grid_result.best_params_)

print("\nBest Cross-Validation Accuracy:")
print(grid_result.best_score_)


# ------------------------------------------------------------
# 7. Get the best ANN model
# ------------------------------------------------------------

best_model = grid_result.best_estimator_


# ------------------------------------------------------------
# 8. Evaluate best model on TEST data
# ------------------------------------------------------------

test_accuracy = best_model.score(
    x_test,
    y_test
)

print("\nTest Accuracy:")
print(test_accuracy)


# ------------------------------------------------------------
# 9. Make predictions on test data
# ------------------------------------------------------------

y_pred = best_model.predict(x_test)

print("\nFirst 10 Predictions:")
print(y_pred[:10])

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001430DB1D4E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 10 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001430DB1D4E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Best Parameters:
{'batch_size': 10, 'epochs': 50, 'model__neurons': 8, 'model__optimizer': 'adam'}

Best Cross-Validation Accuracy:
0.7652597402597402

Test Accuracy:
0.8809523809523809

First 10 Predictions:
[1 0 1 0 1 0 1 1 0 1]

## 4. Evaluation     
●	Employ suitable metrics such as accuracy, precision, recall, and F1-score to evaluate your model's performance.    
●	Discuss the performance differences between the model with default hyperparameters and the tuned model, emphasizing the effects of hyperparameter tuning.    
**Evaluation Criteria**    
●	Accuracy and completeness of the implementation.       
●	Proficiency in data preprocessing and model development.    
●	Systematic approach and thoroughness in hyperparameter tuning.    
●	Depth of evaluation and discussion.    
●	Overall quality of the report.

In [29]:
# Employ suitable metrics for default haparameter:
# Evaluate the Performance 

from sklearn.metrics import (
            accuracy_score,
            precision_score,
            recall_score,
            f1_score,
            roc_auc_score
)


# Accuracy Score
accu_sco = accuracy_score (y_test, y_pred)
print("Accuracy Score:", accu_sco)


# Precision Score
pre_sco = precision_score(y_test, y_pred)
print("Precision Score:",pre_sco)


# Recall Score 
rec_sco = recall_score(y_test, y_pred)
print("Recall Score:", rec_sco)


# F1 Score
f1_sco = f1_score(y_test, y_pred)
print("F1_Score:", f1_sco)

Accuracy Score: 0.8809523809523809
Precision Score: 0.92
Recall Score: 0.8846153846153846
F1_Score: 0.9019607843137255

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8809523809523809

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.88      0.85        16
           1       0.92      0.88      0.90        26

    accuracy                           0.88        42
   macro avg       0.87      0.88      0.88        42
weighted avg       0.88      0.88      0.88        42


Confusion Matrix:
[[14  2]
 [ 3 23]]

**● Discuss the performance differences between the model with default hyperparameters and the tuned model, emphasizing the effects of hyperparameter tuning.**   
The model with default hyperparameters achieved an accuracy of 69.05%. Its classification report showed a precision of 100% and recall of 50% for class 1, indicating that although the model made highly reliable positive predictions, it failed to identify half of the actual class-1 instances. The confusion matrix confirmed this behavior, with 13 false-negative predictions and no false-positive predictions for class 1.   

After hyperparameter tuning, the model achieved a best cross-validation accuracy of 74.10% and a test accuracy of 78.57%. Compared with the default model's test accuracy of 69.05%, the tuned model improved performance by approximately 9.52 percentage points. This improvement indicates that selecting more appropriate hyperparameter values helped the model learn the underlying patterns more effectively and improved its ability to generalize to unseen data.   

Overall, the hyperparameter-tuned model performed better than the default model based on test accuracy. Therefore, the tuned model is preferred for the final implementation. However, precision, recall, and F1-score should also be calculated for the tuned model to determine whether the improvement in accuracy is accompanied by better performance across both classes.

# Additional Resources : 
●	TensorFlow Documentation    
●	Keras Documentation    
We wish you the best of luck with this assignment. Enjoy exploring the fascinating world of neural networks and the power of hyperparameter tuning!